worker_processes 1;
error_log /dev/stderr;
pid /tmp/nginx-x2i.pid;

events {
    worker_connections 128;
}

http {
    access_log /dev/stdout;

    server {
        listen 8088;

        location / {
            proxy_pass http://localhost:8087;
            proxy_set_header Host $host;
        }

        location /ping {
            return 200 'pong';
            add_header Content-Type text/plain;
        }
    }
}
