[agent]
  interval = "5s"
  round_interval = false
  metric_batch_size = 5000
  metric_buffer_limit = 100000
  flush_interval = "5s"
  flush_jitter = "0s"

[[inputs.influxdb_listener]]
  service_address = ":8087"
  parser_type = "upstream"
  read_timeout = "10s"
  write_timeout = "10s"
  [inputs.influxdb_listener.tags]
    source = "x2i_gatling"

[[outputs.influxdb_v2]]
  urls = ["${INFLUX_HOST}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
